import React from 'react';
import { StyleSheet, View, type ViewProps } from 'react-native';
import Svg, { Circle, G, Line, Path, Polygon, Polyline, Rect, Text as SvgText } from 'react-native-svg';

import { useThompsonTheme } from '../theme';
import { Text } from './typography';

export interface ChartSeries { color?: string; key: string; name: string; }
export const chartPalette = ['#2f6b8f', '#d8895b', '#cfaa62', '#6a8e7f', '#895f7a', '#4d7c98', '#b96a4b', '#81965b'];
export const chartTheme = { palette: chartPalette, colors: { sea: chartPalette[0], sunset: chartPalette[1], desert: chartPalette[2] }, axis: {}, grid: {}, tooltip: {} };
export function pickColor(index: number) { return chartPalette[Math.abs(index) % chartPalette.length]; }

export interface ChartProps extends ViewProps { data?: Record<string, unknown>[]; height?: number; }
export function Chart({ children, height = 300, style, ...props }: ChartProps) { return <View style={[{ height, width: '100%' }, style]} {...props}>{children}</View>; }

const W = 320;
function values(data: Record<string, unknown>[], key: string) { return data.map((row) => Number(row[key]) || 0); }
function points(data: Record<string, unknown>[], key: string, height: number, inset = 14) { const vals = values(data, key); const max = Math.max(...vals, 1); const min = Math.min(...vals, 0); const span = Math.max(1, max - min); return vals.map((value, index) => ({ x: inset + index * ((W - inset * 2) / Math.max(1, vals.length - 1)), y: inset + (1 - (value - min) / span) * (height - inset * 2) })); }
function pointString(input: Array<{ x: number; y: number }>) { return input.map((point) => `${point.x},${point.y}`).join(' '); }
function Legend({ series }: { series: ChartSeries[] }) { return <View style={styles.legend}>{series.map((item, index) => <View key={item.key} style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: item.color ?? chartPalette[index % chartPalette.length] }]} /><Text size='xs' tone='secondary'>{item.name}</Text></View>)}</View>; }
function Grid({ height }: { height: number }) { const { theme } = useThompsonTheme(); return <G>{[0.25, 0.5, 0.75].map((ratio) => <Line key={ratio} x1={8} x2={W - 8} y1={height * ratio} y2={height * ratio} stroke={theme.colors.border} strokeDasharray='3 5' />)}</G>; }

export interface LineChartProps { data: Record<string, unknown>[]; height?: number; series: ChartSeries[]; showGrid?: boolean; showLegend?: boolean; xAxisKey: string; xAxisLabel?: string; yAxisLabel?: string; yAxisTickFormatter?: (value: number) => string; tooltipFormatter?: (value: number) => string; }
export function LineChart({ data, height = 300, series, showGrid = true, showLegend = true }: LineChartProps) { const plotHeight = showLegend ? height - 36 : height; return <Chart height={height}><Svg height={plotHeight} viewBox={`0 0 ${W} ${plotHeight}`} width='100%'>{showGrid ? <Grid height={plotHeight} /> : null}{series.map((item, index) => <Polyline key={item.key} fill='none' points={pointString(points(data, item.key, plotHeight))} stroke={item.color ?? chartPalette[index % chartPalette.length]} strokeLinecap='round' strokeLinejoin='round' strokeWidth={2.5} />)}</Svg>{showLegend ? <Legend series={series} /> : null}</Chart>; }
export interface AreaChartProps extends Omit<LineChartProps, 'xAxisLabel' | 'yAxisLabel'> { stacked?: boolean; }
export function AreaChart({ data, height = 300, series, showGrid = true, showLegend = true }: AreaChartProps) { const plotHeight = showLegend ? height - 36 : height; return <Chart height={height}><Svg height={plotHeight} viewBox={`0 0 ${W} ${plotHeight}`} width='100%'>{showGrid ? <Grid height={plotHeight} /> : null}{series.map((item, index) => { const line = points(data, item.key, plotHeight); const fill = `${pointString(line)} ${W - 14},${plotHeight - 14} 14,${plotHeight - 14}`; const color = item.color ?? chartPalette[index % chartPalette.length]; return <G key={item.key}><Polygon fill={color} fillOpacity={0.16} points={fill} /><Polyline fill='none' points={pointString(line)} stroke={color} strokeWidth={2.5} /></G>; })}</Svg>{showLegend ? <Legend series={series} /> : null}</Chart>; }
export interface BarChartProps extends Omit<LineChartProps, 'xAxisLabel' | 'yAxisLabel'> { layout?: 'horizontal' | 'vertical'; }
export function BarChart({ data, height = 300, series, showGrid = true, showLegend = true }: BarChartProps) { const plotHeight = showLegend ? height - 36 : height; const max = Math.max(...series.flatMap((item) => values(data, item.key)), 1); const group = (W - 24) / Math.max(1, data.length); const bar = Math.max(3, (group - 6) / Math.max(1, series.length)); return <Chart height={height}><Svg height={plotHeight} viewBox={`0 0 ${W} ${plotHeight}`} width='100%'>{showGrid ? <Grid height={plotHeight} /> : null}{data.flatMap((row, rowIndex) => series.map((item, seriesIndex) => { const value = Number(row[item.key]) || 0; const h = value / max * (plotHeight - 28); return <Rect key={`${rowIndex}:${item.key}`} fill={item.color ?? chartPalette[seriesIndex % chartPalette.length]} height={h} rx={3} width={bar} x={12 + rowIndex * group + 3 + seriesIndex * bar} y={plotHeight - 14 - h} />; }))}</Svg>{showLegend ? <Legend series={series} /> : null}</Chart>; }

export interface SparklineProps { color?: string; data: Record<string, unknown>[]; dataKey: string; height?: number; showArea?: boolean; }
export function Sparkline({ color = chartPalette[0], data, dataKey, height = 40, showArea = false }: SparklineProps) { const line = points(data, dataKey, height, 2); return <Svg height={height} viewBox={`0 0 ${W} ${height}`} width='100%'>{showArea ? <Polygon fill={color} fillOpacity={0.14} points={`${pointString(line)} ${W - 2},${height - 2} 2,${height - 2}`} /> : null}<Polyline fill='none' points={pointString(line)} stroke={color} strokeWidth={2} /></Svg>; }

export interface PieChartDatum { color?: string; name: string; value: number; }
export interface PieChartProps { data: PieChartDatum[]; dataKey?: string; height?: number; innerRadius?: number | string; nameKey?: string; showLegend?: boolean; }
function polar(cx: number, cy: number, radius: number, angle: number) { const radians = (angle - 90) * Math.PI / 180; return { x: cx + radius * Math.cos(radians), y: cy + radius * Math.sin(radians) }; }
function arcPath(start: number, end: number, outer: number, inner = 0) { const cx = W / 2, cy = 125; const a = polar(cx, cy, outer, end), b = polar(cx, cy, outer, start); const large = end - start > 180 ? 1 : 0; if (!inner) return `M ${cx} ${cy} L ${a.x} ${a.y} A ${outer} ${outer} 0 ${large} 0 ${b.x} ${b.y} Z`; const c = polar(cx, cy, inner, start), d = polar(cx, cy, inner, end); return `M ${a.x} ${a.y} A ${outer} ${outer} 0 ${large} 0 ${b.x} ${b.y} L ${c.x} ${c.y} A ${inner} ${inner} 0 ${large} 1 ${d.x} ${d.y} Z`; }
export function PieChart({ data, height = 300, innerRadius = 0, showLegend = true }: PieChartProps) { const total = Math.max(1, data.reduce((sum, item) => sum + item.value, 0)); let angle = 0; const inner = typeof innerRadius === 'number' ? innerRadius : innerRadius === '60%' ? 55 : 0; return <Chart height={height}><Svg height={showLegend ? height - 40 : height} viewBox={`0 0 ${W} 250`} width='100%'>{data.map((item, index) => { const start = angle; angle += item.value / total * 359.5; return <Path key={item.name} d={arcPath(start, angle, 100, inner)} fill={item.color ?? chartPalette[index % chartPalette.length]} />; })}</Svg>{showLegend ? <Legend series={data.map((item) => ({ key: item.name, name: item.name, color: item.color }))} /> : null}</Chart>; }
export interface DonutChartProps { centerLabel?: string; centerValue?: string; data: PieChartDatum[]; height?: number; showLegend?: boolean; }
export function DonutChart({ centerLabel, centerValue, ...props }: DonutChartProps) { return <View><PieChart {...props} innerRadius='60%' />{centerValue || centerLabel ? <View pointerEvents='none' style={styles.center}>{centerValue ? <Text size='lg' weight='600'>{centerValue}</Text> : null}{centerLabel ? <Text size='xs' tone='secondary'>{centerLabel}</Text> : null}</View> : null}</View>; }

export interface ScatterSeries extends ChartSeries { data?: Record<string, unknown>[]; xKey: string; yKey: string; zKey?: string; }
export interface ScatterChartProps { data: Record<string, unknown>[]; height?: number; series: ScatterSeries[]; showGrid?: boolean; showLegend?: boolean; xAxisLabel?: string; yAxisLabel?: string; xAxisTickFormatter?: (value: number | string) => string; yAxisTickFormatter?: (value: number | string) => string; tooltipFormatter?: (value: number) => string; }
export function ScatterChart({ data, height = 350, series, showGrid = true, showLegend = true }: ScatterChartProps) { const plotHeight = showLegend ? height - 36 : height; return <Chart height={height}><Svg height={plotHeight} viewBox={`0 0 ${W} ${plotHeight}`} width='100%'>{showGrid ? <Grid height={plotHeight} /> : null}{series.flatMap((item, seriesIndex) => { const rows = item.data ?? data; const xs = values(rows, item.xKey), ys = values(rows, item.yKey), maxX = Math.max(...xs, 1), maxY = Math.max(...ys, 1); return rows.map((row, index) => <Circle key={`${item.key}:${index}`} cx={14 + xs[index] / maxX * (W - 28)} cy={plotHeight - 14 - ys[index] / maxY * (plotHeight - 28)} fill={item.color ?? chartPalette[seriesIndex % chartPalette.length]} opacity={0.75} r={item.zKey ? Math.max(3, Math.sqrt(Number(row[item.zKey]) || 9)) : 5} />); })}</Svg>{showLegend ? <Legend series={series} /> : null}</Chart>; }

export interface RadarSeries extends ChartSeries { fill?: boolean; }
export interface RadarChartProps { data: Record<string, unknown>[]; height?: number; series: RadarSeries[]; showLegend?: boolean; subjectKey: string; tickFormatter?: (value: number) => string; }
export function RadarChart({ data, height = 350, series, showLegend = true }: RadarChartProps) { const plotHeight = showLegend ? height - 36 : height, cx = W / 2, cy = plotHeight / 2, radius = Math.min(120, plotHeight / 2 - 18); const max = Math.max(...series.flatMap((item) => values(data, item.key)), 1); const axis = data.map((_, index) => polar(cx, cy, radius, index * 360 / data.length)); return <Chart height={height}><Svg height={plotHeight} viewBox={`0 0 ${W} ${plotHeight}`} width='100%'><Polygon fill='none' points={pointString(axis)} stroke='#999' opacity={0.3} />{axis.map((point, index) => <Line key={index} x1={cx} y1={cy} x2={point.x} y2={point.y} stroke='#999' opacity={0.25} />)}{series.map((item, s) => <Polygon key={item.key} fill={item.color ?? chartPalette[s]} fillOpacity={item.fill ? 0.25 : 0.08} points={pointString(data.map((row, index) => polar(cx, cy, radius * ((Number(row[item.key]) || 0) / max), index * 360 / data.length)))} stroke={item.color ?? chartPalette[s]} strokeWidth={2} />)}</Svg>{showLegend ? <Legend series={series} /> : null}</Chart>; }

export interface RadialBarChartDatum { fill?: string; name: string; value: number; }
export interface RadialBarChartProps { data: RadialBarChartDatum[]; endAngle?: number; height?: number; innerRadius?: string | number; outerRadius?: string | number; showLegend?: boolean; startAngle?: number; }
export function RadialBarChart({ data, height = 350, showLegend = true }: RadialBarChartProps) { const max = Math.max(...data.map((item) => item.value), 1); return <Chart height={height}><Svg height={height - (showLegend ? 40 : 0)} viewBox={`0 0 ${W} 250`} width='100%'>{data.map((item, index) => <Path key={item.name} d={arcPath(0, item.value / max * 359, 105 - index * 18, 94 - index * 18)} fill={item.fill ?? chartPalette[index]} />)}</Svg>{showLegend ? <Legend series={data.map((item) => ({ key: item.name, name: item.name, color: item.fill }))} /> : null}</Chart>; }

export interface FunnelChartDatum { fill?: string; name: string; value: number; }
export interface FunnelChartProps { data: FunnelChartDatum[]; height?: number; showLabels?: boolean; valueFormatter?: (value: number) => string; }
export function FunnelChart({ data, height = 350, showLabels = true, valueFormatter }: FunnelChartProps) { const max = Math.max(...data.map((item) => item.value), 1), row = height / Math.max(1, data.length); return <Svg height={height} viewBox={`0 0 ${W} ${height}`} width='100%'>{data.map((item, index) => { const top = item.value / max * 280, next = (data[index + 1]?.value ?? item.value * 0.75) / max * 280, y = index * row; return <G key={item.name}><Polygon fill={item.fill ?? chartPalette[index % chartPalette.length]} points={`${(W-top)/2},${y} ${(W+top)/2},${y} ${(W+next)/2},${y+row-3} ${(W-next)/2},${y+row-3}`} />{showLabels ? <SvgText fill='#fff' fontSize={11} textAnchor='middle' x={W/2} y={y+row/2}>{item.name}: {valueFormatter?.(item.value) ?? item.value}</SvgText> : null}</G>; })}</Svg>; }

export interface SankeyNode { fill?: string; name: string; }
export interface SankeyLink { source: number; target: number; value: number; }
export interface SankeyChartProps { data: { links: SankeyLink[]; nodes: SankeyNode[] }; height?: number; linkCurvature?: number; linkOpacity?: number; nodeColors?: string[]; nodeRadius?: number; nodeWidth?: number; }
export function SankeyChart({ data, height = 400, linkOpacity = 0.35, nodeColors = chartPalette, nodeRadius = 4, nodeWidth = 12 }: SankeyChartProps) { const positions = data.nodes.map((_, index) => ({ x: index % 2 === 0 ? 24 : W - 24 - nodeWidth, y: 20 + index * ((height - 40) / Math.max(1, data.nodes.length - 1)) })); return <Svg height={height} viewBox={`0 0 ${W} ${height}`} width='100%'>{data.links.map((link, index) => { const a=positions[link.source], b=positions[link.target]; return a&&b ? <Path key={index} d={`M ${a.x+nodeWidth} ${a.y+10} C ${W/2} ${a.y+10}, ${W/2} ${b.y+10}, ${b.x} ${b.y+10}`} fill='none' opacity={linkOpacity} stroke={nodeColors[link.source%nodeColors.length]} strokeWidth={Math.max(2, link.value)} /> : null; })}{data.nodes.map((node,index)=><G key={`${node.name}:${index}`}><Rect fill={node.fill??nodeColors[index%nodeColors.length]} height={22} rx={nodeRadius} width={nodeWidth} x={positions[index].x} y={positions[index].y}/><SvgText fill='#666' fontSize={10} x={positions[index].x < W/2 ? positions[index].x+18 : positions[index].x-4} y={positions[index].y+14} textAnchor={positions[index].x < W/2 ? 'start':'end'}>{node.name}</SvgText></G>)}</Svg>; }

export interface SunburstNode { children?: SunburstNode[]; fill?: string; name: string; value?: number; }
export interface SunburstChartProps { data: SunburstNode; dataKey?: string; height?: number; nameKey?: string; }
export function SunburstChart({ data, height = 350 }: SunburstChartProps) { const nodes = data.children ?? [data], total = Math.max(1, nodes.reduce((sum,node)=>sum+(node.value??0),0)); let angle=0; return <Svg height={height} viewBox={`0 0 ${W} 250`} width='100%'>{nodes.map((node,index)=>{const start=angle; angle+=(node.value??0)/total*359; return <Path key={`${node.name}:${index}`} d={arcPath(start,angle,105,35)} fill={node.fill??chartPalette[index%chartPalette.length]}/>;})}<SvgText fill='#666' fontSize={12} textAnchor='middle' x={W/2} y={129}>{data.name}</SvgText></Svg>; }

const styles = StyleSheet.create({ center: { alignItems: 'center', left: 0, position: 'absolute', right: 0, top: 105 }, legend: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'center' }, legendDot: { borderRadius: 99, height: 8, width: 8 }, legendItem: { alignItems: 'center', flexDirection: 'row', gap: 4 } });
