import React from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, View, type FlatListProps, type ViewProps } from 'react-native';
import { spacing } from '@gaulatti/bleecker/tokens';

import { useThompsonTheme } from '../theme';
import { Button } from './button';
import { FilterGroup, type FilterChipProps } from './filter-chip';
import { SearchInput } from './search-input';
import { Select, type SelectOption } from './advanced-inputs';
import { Text } from './typography';

export interface DataTableColumn<T> { align?: 'left' | 'center' | 'right'; id: string; render?: (row: T) => React.ReactNode; title: string; value?: (row: T) => React.ReactNode; width?: number; }
export interface DataTableProps<T> extends Omit<FlatListProps<T>, 'data' | 'renderItem'> { columns: DataTableColumn<T>[]; data: readonly T[]; empty?: React.ReactNode; getRowId?: (row: T, index: number) => string; onRowPress?: (row: T) => void; }
export function DataTable<T>({ columns, data, empty, getRowId, onRowPress, ...props }: DataTableProps<T>) { const { theme } = useThompsonTheme(); return <ScrollView horizontal><View style={styles.table}><View style={[styles.row, styles.header, { borderBottomColor: theme.colors.border }]}>{columns.map((column) => <View key={column.id} style={[styles.cell, { width: column.width ?? 140 }]}><Text size='xs' tone='secondary' weight='600'>{column.title.toUpperCase()}</Text></View>)}</View><FlatList data={[...data]} keyExtractor={(row, index) => getRowId?.(row, index) ?? String(index)} ListEmptyComponent={<View>{empty ?? <Text tone='secondary'>No rows</Text>}</View>} renderItem={({ item }) => <Pressable disabled={!onRowPress} onPress={() => onRowPress?.(item)} style={[styles.row, { borderBottomColor: theme.colors.border }]}>{columns.map((column) => <View key={column.id} style={[styles.cell, { width: column.width ?? 140, alignItems: column.align === 'right' ? 'flex-end' : column.align === 'center' ? 'center' : 'flex-start' }]}>{column.render?.(item) ?? column.value?.(item) ?? <Text size='sm'>{String((item as Record<string, unknown>)[column.id] ?? '')}</Text>}</View>)}</Pressable>} {...props} /></View></ScrollView>; }
export const Table = DataTable;

export interface DataTableToolbarProps extends ViewProps { actions?: React.ReactNode; onSearchChange?: (value: string) => void; searchPlaceholder?: string; searchValue?: string; }
export function DataTableToolbar({ actions, onSearchChange, searchPlaceholder = 'Search rows', searchValue, style, ...props }: DataTableToolbarProps) { return <View style={[styles.toolbar, style]} {...props}><View style={styles.grow}><SearchInput onChangeText={onSearchChange} placeholder={searchPlaceholder} value={searchValue} /></View>{actions}</View>; }
export interface DataTableFiltersProps extends ViewProps { filters: FilterChipProps[]; onClearAll?: () => void; }
export function DataTableFilters({ filters, onClearAll, ...props }: DataTableFiltersProps) { return <FilterGroup filters={filters} onClearAll={onClearAll} {...props} />; }
export interface DataTableSelectFilterProps<TData> extends ViewProps { columnId: string; options: SelectOption[]; placeholder?: string; table: { getColumn(id: string): { getFilterValue(): unknown; setFilterValue(value: unknown): void } | undefined }; }
export function DataTableSelectFilter<TData>({ columnId, options, placeholder = 'All', style, table, ...props }: DataTableSelectFilterProps<TData>) { const column = table.getColumn(columnId); if (!column) return null; const value = String(column.getFilterValue() ?? ''); return <View style={style} {...props}><Select onValueChange={(next) => column.setFilterValue(next || undefined)} options={[{ label: placeholder, value: '' }, ...options]} placeholder={placeholder} value={value} /></View>; }
export interface DataTableFacetedFilterProps<TData, TValue = string> extends ViewProps { column?: { getFilterValue(): unknown; setFilterValue(value: unknown): void }; options: Array<{ icon?: React.ComponentType<Record<string, unknown>>; label: string; value: TValue }>; title?: string; }
export interface DataTableColumnToggleProps<T> extends ViewProps { columns: DataTableColumn<T>[]; hidden: string[]; onChange: (hidden: string[]) => void; }
export function DataTableColumnToggle<T>({ columns, hidden, onChange, style, ...props }: DataTableColumnToggleProps<T>) { return <View style={[styles.wrap, style]} {...props}>{columns.map((column) => <Pressable key={column.id} onPress={() => onChange(hidden.includes(column.id) ? hidden.filter((id) => id !== column.id) : [...hidden, column.id])}><Text size='xs' tone={hidden.includes(column.id) ? 'secondary' : 'accent'}>{hidden.includes(column.id) ? '○' : '●'} {column.title}</Text></Pressable>)}</View>; }
export interface DataTablePaginationProps extends ViewProps { currentPage: number; onPageChange: (page: number) => void; pageSize?: number; total: number; }
export function DataTablePagination({ currentPage, onPageChange, pageSize = 20, style, total, ...props }: DataTablePaginationProps) { const pages = Math.max(1, Math.ceil(total / pageSize)); return <View style={[styles.toolbar, style]} {...props}><Text size='xs' tone='secondary'>{total} rows · Page {currentPage} of {pages}</Text><View style={styles.wrap}><Button disabled={currentPage <= 1} size='xs' variant='ghost' onPress={() => onPageChange(currentPage - 1)}>Previous</Button><Button disabled={currentPage >= pages} size='xs' variant='ghost' onPress={() => onPageChange(currentPage + 1)}>Next</Button></View></View>; }

const styles = StyleSheet.create({ cell: { justifyContent: 'center', paddingHorizontal: spacing.control, paddingVertical: spacing.control }, grow: { flex: 1 }, header: { backgroundColor: 'rgba(128,128,128,0.06)' }, row: { borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', minHeight: 44 }, table: { minWidth: '100%' }, toolbar: { alignItems: 'center', flexDirection: 'row', gap: spacing.control, justifyContent: 'space-between' }, wrap: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.control } });
